// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SteamWebApp.DAL.Entity.Concrete.EfCore.Context;

namespace SteamWebApp.DAL.Migrations
{
    [DbContext(typeof(ProjectContext))]
    partial class ProjectContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("SteamWebApp.Entities.Entity.Concrete.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Moba is a team-based strategy game where two teams of five powerful champions face off to destroy the other’s base.",
                            Name = "Moba",
                            Status = 1,
                            TransactionDate = new DateTime(2020, 4, 21, 15, 31, 57, 634, DateTimeKind.Local).AddTicks(2562)
                        },
                        new
                        {
                            Id = 2,
                            Description = "A first person shooter (FPS) is a genre of action video game that is played from the point of view of the protagonist. FPS games typically map the gamer's movements and provide a view of what an actual person would see and do in the game",
                            Name = "Fps",
                            Status = 1,
                            TransactionDate = new DateTime(2020, 4, 21, 15, 31, 57, 634, DateTimeKind.Local).AddTicks(3090)
                        },
                        new
                        {
                            Id = 3,
                            Description = "Survival games are a subgenre of action video games set in a hostile, intense, open-world environment, where players generally begin with minimal equipment and are required to collect resources, craft tools, weapons, and shelter, and survive as long as possible.",
                            Name = "Survival Games",
                            Status = 1,
                            TransactionDate = new DateTime(2020, 4, 21, 15, 31, 57, 634, DateTimeKind.Local).AddTicks(3099)
                        });
                });

            modelBuilder.Entity("SteamWebApp.Entities.Entity.Concrete.CategoryGame", b =>
                {
                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.HasKey("GameId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("CategoryGame");

                    b.HasData(
                        new
                        {
                            GameId = 1,
                            CategoryId = 1
                        },
                        new
                        {
                            GameId = 2,
                            CategoryId = 2
                        },
                        new
                        {
                            GameId = 3,
                            CategoryId = 2
                        },
                        new
                        {
                            GameId = 3,
                            CategoryId = 3
                        },
                        new
                        {
                            GameId = 4,
                            CategoryId = 1
                        },
                        new
                        {
                            GameId = 5,
                            CategoryId = 1
                        },
                        new
                        {
                            GameId = 6,
                            CategoryId = 3
                        },
                        new
                        {
                            GameId = 6,
                            CategoryId = 2
                        },
                        new
                        {
                            GameId = 7,
                            CategoryId = 1
                        },
                        new
                        {
                            GameId = 8,
                            CategoryId = 2
                        },
                        new
                        {
                            GameId = 9,
                            CategoryId = 3
                        },
                        new
                        {
                            GameId = 10,
                            CategoryId = 3
                        });
                });

            modelBuilder.Entity("SteamWebApp.Entities.Entity.Concrete.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("UserId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("SteamWebApp.Entities.Entity.Concrete.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "(LoL) is a multiplayer online battle arena video game developed and published by Riot Games for Microsoft Windows and macOS. Inspired by the Warcraft III: The Frozen Throne mod Defense of the Ancients, the game follows a freemium model and is supported by microtransactions.",
                            Image = "lol.jpg",
                            Name = "League Of Legends",
                            Price = 120m,
                            Status = 1,
                            TransactionDate = new DateTime(2020, 4, 21, 15, 31, 57, 635, DateTimeKind.Local).AddTicks(3621)
                        },
                        new
                        {
                            Id = 2,
                            Description = "The Terrorists, depending on the game mode, must either plant the bomb or defend the hostages, while the Counter-Terrorists must either prevent the bomb from being planted, defuse the bomb, or rescue the hostages",
                            Image = "csgo.jpg",
                            Name = "CsGo",
                            Price = 0m,
                            Status = 1,
                            TransactionDate = new DateTime(2020, 4, 21, 15, 31, 57, 635, DateTimeKind.Local).AddTicks(5405)
                        },
                        new
                        {
                            Id = 3,
                            Description = "Battlegrounds is a player versus player shooter game in which up to one hundred players fight in a battle royale, a type of large-scale last man standing deathmatch where players fight to remain the last alive. Players can choose to enter the match solo, duo, or with a small team of up to four people.",
                            Image = "battleground.jpg",
                            Name = "Battleground",
                            Price = 50m,
                            Status = 1,
                            TransactionDate = new DateTime(2020, 4, 21, 15, 31, 57, 635, DateTimeKind.Local).AddTicks(5440)
                        },
                        new
                        {
                            Id = 4,
                            Description = "Dota 2 is a multiplayer online battle arena (MOBA) video game in which two teams of five players compete to collectively destroy a large structure defended by the opposing team known as the Ancient, whilst defending their own.",
                            Image = "dota2.jpg",
                            Name = "Dota2",
                            Price = 25m,
                            Status = 1,
                            TransactionDate = new DateTime(2020, 4, 21, 15, 31, 57, 635, DateTimeKind.Local).AddTicks(5443)
                        },
                        new
                        {
                            Id = 5,
                            Description = "SMITE is the MOBA (Multiplayer Online Battle Arena) type game in which the players fight with each other on the particular map within a special set of rules. Each of the players controls one character, in SMITE the characters are Gods.",
                            Image = "smite.jpg",
                            Name = "Smite",
                            Price = 0m,
                            Status = 1,
                            TransactionDate = new DateTime(2020, 4, 21, 15, 31, 57, 635, DateTimeKind.Local).AddTicks(5444)
                        },
                        new
                        {
                            Id = 6,
                            Description = "Z1 Battle Royale (formerly H1Z1 and King of the Kill) is a free-to-play battle royale game developed and published by Daybreak Game Company. The game's development began after the original H1Z1 was spun off into two separate projects in early 2016: H1Z1: Just Survive and H1Z1: King of the Kill.",
                            Image = "h1z1.jpg",
                            Name = "H1Z1",
                            Price = 15m,
                            Status = 1,
                            TransactionDate = new DateTime(2020, 4, 21, 15, 31, 57, 635, DateTimeKind.Local).AddTicks(5446)
                        },
                        new
                        {
                            Id = 7,
                            Description = "Paragon was a free-to-play multiplayer online battle arena game developed and published by Epic Games. Powered by their own Unreal Engine 4, the game started pay-to-play early access in March 2016, and free-to-play access to its open beta started in February 2017.",
                            Image = "paragon.jpg",
                            Name = "Paragon",
                            Price = 0m,
                            Status = 1,
                            TransactionDate = new DateTime(2020, 4, 21, 15, 31, 57, 635, DateTimeKind.Local).AddTicks(5447)
                        },
                        new
                        {
                            Id = 8,
                            Description = "Gameplay. Valorant is a team-based tactical shooter and first-person shooter set in the near-future. ... In the main game mode, players join either the attacking or defending team with each team having five players on it. Agents have unique abilities and use an economic system to purchase their abilities and weapons.",
                            Image = "valorant.jpg",
                            Name = "Valorant",
                            Price = 60m,
                            Status = 1,
                            TransactionDate = new DateTime(2020, 4, 21, 15, 31, 57, 635, DateTimeKind.Local).AddTicks(5449)
                        },
                        new
                        {
                            Id = 9,
                            Description = "Raft throws you and your friends into an epic oceanic adventure! Alone or together, players battle to survive a perilous voyage across a vast sea! Gather debris, scavenge reefs and build your own floating home, but be wary of the man-eating sharks!",
                            Image = "raft.jpg",
                            Name = "Raft",
                            Price = 0m,
                            Status = 1,
                            TransactionDate = new DateTime(2020, 4, 21, 15, 31, 57, 635, DateTimeKind.Local).AddTicks(5450)
                        },
                        new
                        {
                            Id = 10,
                            Description = "Minecraft is a Lego style adventure game which has massively increased in popularity since it was released two years ago. It now has more than 33 million users worldwide. The video game puts players in a randomly-generated world where they can create their own structures and contraptions out of textured cubes",
                            Image = "minecraft.jpg",
                            Name = "Minecraft",
                            Price = 140m,
                            Status = 1,
                            TransactionDate = new DateTime(2020, 4, 21, 15, 31, 57, 635, DateTimeKind.Local).AddTicks(5451)
                        });
                });

            modelBuilder.Entity("SteamWebApp.Entities.Entity.Concrete.GameUser", b =>
                {
                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("GameId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("GameUser");
                });

            modelBuilder.Entity("SteamWebApp.Entities.Entity.Concrete.Like", b =>
                {
                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("GameId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("Like");
                });

            modelBuilder.Entity("SteamWebApp.Entities.Entity.Concrete.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("SteamWebApp.Entities.Entity.Concrete.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("SteamWebApp.Entities.Entity.Concrete.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SteamWebApp.Entities.Entity.Concrete.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("SteamWebApp.Entities.Entity.Concrete.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SteamWebApp.Entities.Entity.Concrete.CategoryGame", b =>
                {
                    b.HasOne("SteamWebApp.Entities.Entity.Concrete.Category", "Category")
                        .WithMany("CategoryGames")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SteamWebApp.Entities.Entity.Concrete.Game", "Game")
                        .WithMany("CategoryGames")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SteamWebApp.Entities.Entity.Concrete.Comment", b =>
                {
                    b.HasOne("SteamWebApp.Entities.Entity.Concrete.Game", "Game")
                        .WithMany("Comments")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SteamWebApp.Entities.Entity.Concrete.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("SteamWebApp.Entities.Entity.Concrete.GameUser", b =>
                {
                    b.HasOne("SteamWebApp.Entities.Entity.Concrete.Game", "Game")
                        .WithMany("GameUsers")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SteamWebApp.Entities.Entity.Concrete.User", null)
                        .WithMany("GameUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SteamWebApp.Entities.Entity.Concrete.Like", b =>
                {
                    b.HasOne("SteamWebApp.Entities.Entity.Concrete.Game", "Game")
                        .WithMany("Likes")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SteamWebApp.Entities.Entity.Concrete.User", null)
                        .WithMany("Likes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
